server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Force Nginx to serve .mjs files with the correct Javascript MIME type
    location ~ \.mjs$ {
        types {
            application/javascript mjs;
        }
    }
}
